# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
  - mysql

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    - php: 7.0

# Update composer
before-install:
  - composer self-update

# Run script
script:
  - phpunit

deploy:
  provider: pages
  skip-cleanup: true
  github-token: 1991fae2838c4c3b5ab47b619c8ddde2e8da6bef  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: dev
